### PR TITLE
Bump version to support angular 6.0.0 and rxjs 6 syntax

### PR DESCRIPTION
**Pull request by ivalexa**

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
@atul-wizni any timeline on this getting merged and released?

**Comment by miniprice** [comment]
Any chance this can be prioritised?  Would love to be able to upgrade my app and its dependencies to Angular 6.

**Comment by j2L4e** [comment]
@miniprice you can by installing the `rxjs-compat` package until all your dependencies work with rxjs6

**Comment by atul-wizni** [comment]
published ngx-monaco-editor@6.0.0

**Pull request merged**
